# Generated by Django 3.0.3 on 2020-07-09 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id_company', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('addr', models.CharField(max_length=200)),
                ('tel', models.CharField(blank=True, max_length=20, null=True)),
                ('info', models.CharField(blank=True, max_length=3000, null=True)),
                ('category', models.CharField(blank=True, max_length=15, null=True)),
                ('img', models.CharField(blank=True, max_length=2000, null=True)),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'company',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('dong', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('gu', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'location',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id_log', models.AutoField(primary_key=True, serialize=False)),
                ('search', models.CharField(max_length=60)),
                ('cdate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Manner',
            fields=[
                ('id_manner', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.FloatField()),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'manner',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MannerLog',
            fields=[
                ('id_manner_log', models.IntegerField(primary_key=True, serialize=False)),
                ('score', models.FloatField()),
                ('cdate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'manner_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MannerReviewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'manner_reviewer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id_member', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('user_id', models.CharField(max_length=30, unique=True)),
                ('user_pw', models.CharField(max_length=300)),
                ('nick_name', models.CharField(max_length=30)),
                ('tel', models.CharField(max_length=20)),
                ('birth', models.DateField()),
                ('email', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=6)),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(null=True)),
                ('last_date', models.DateTimeField(null=True)),
                ('img', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'member',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Memberaddr',
            fields=[
                ('id_member_addr', models.AutoField(primary_key=True, serialize=False)),
                ('addr', models.CharField(max_length=200)),
                ('distance', models.IntegerField(default=0)),
                ('select', models.CharField(default='Y', max_length=8)),
            ],
            options={
                'db_table': 'memberaddr',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id_product', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('info', models.CharField(max_length=3000)),
                ('category', models.CharField(blank=True, max_length=15, null=True)),
                ('views', models.IntegerField(default=0)),
                ('state', models.CharField(default='판매중', max_length=10)),
                ('addr', models.CharField(max_length=200)),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id_rate', models.IntegerField(primary_key=True, serialize=False)),
                ('field', models.CharField(max_length=8)),
                ('detail', models.CharField(max_length=50)),
                ('score', models.FloatField()),
            ],
            options={
                'db_table': 'rate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RealDeal',
            fields=[
                ('id_real_deal', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'real_deal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SellerRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'seller_rate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SellerReview',
            fields=[
                ('id_review_seller', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=100)),
                ('cdate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'seller_review',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShopperRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'shopper_rate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShopperReview',
            fields=[
                ('id_review_shopper', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=100)),
                ('cdate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'shopper_review',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id_wishlist', models.AutoField(primary_key=True, serialize=False)),
                ('cdate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'wishlist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nearby_Location',
            fields=[
                ('dong', models.OneToOneField(db_column='dong', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='member.Location')),
                ('nearby_dong', models.CharField(max_length=20)),
                ('distance', models.IntegerField()),
            ],
            options={
                'db_table': 'nearby_location',
                'managed': False,
            },
        ),
    ]
