# Generated by Django 3.0.3 on 2020-07-06 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('dong', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=0, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
            options={
                'db_table': 'location',
            },
        ),
        migrations.CreateModel(
            name='Manner',
            fields=[
                ('id_manner', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.FloatField()),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'manner',
            },
        ),
        migrations.CreateModel(
            name='MannerLog',
            fields=[
                ('id_manner_log', models.IntegerField(primary_key=True, serialize=False)),
                ('score', models.FloatField()),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('id_manner', models.ForeignKey(db_column='id_manner', on_delete=django.db.models.deletion.DO_NOTHING, to='member.Manner')),
            ],
            options={
                'db_table': 'manner_log',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id_member', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('user_id', models.CharField(max_length=30)),
                ('user_pw', models.CharField(max_length=55)),
                ('nick_name', models.CharField(max_length=30)),
                ('tel', models.CharField(max_length=20)),
                ('birth', models.DateField()),
                ('email', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=6)),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(null=True)),
                ('last_date', models.DateTimeField(null=True)),
                ('img', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'member',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id_product', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('info', models.CharField(max_length=3000)),
                ('category', models.CharField(blank=True, max_length=15, null=True)),
                ('img', models.CharField(blank=True, max_length=2000, null=True)),
                ('views', models.IntegerField(default=0)),
                ('sold_tf', models.IntegerField(db_column='sold_TF', default=0)),
                ('addr', models.CharField(max_length=200)),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id_member', models.ForeignKey(db_column='id_member', on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id_rate', models.IntegerField(primary_key=True, serialize=False)),
                ('field', models.CharField(max_length=8)),
                ('detail', models.CharField(max_length=50)),
                ('score', models.FloatField()),
            ],
            options={
                'db_table': 'rate',
            },
        ),
        migrations.CreateModel(
            name='RealDeal',
            fields=[
                ('id_real_deal', models.AutoField(primary_key=True, serialize=False)),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('id_product', models.ForeignKey(db_column='id_product', on_delete=django.db.models.deletion.DO_NOTHING, to='member.Product')),
            ],
            options={
                'db_table': 'real_deal',
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id_wishlist', models.AutoField(primary_key=True, serialize=False)),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('id_member', models.ForeignKey(db_column='id_member', on_delete=django.db.models.deletion.PROTECT, to='member.Member')),
                ('id_product', models.ForeignKey(db_column='id_product', on_delete=django.db.models.deletion.PROTECT, to='member.Product')),
            ],
            options={
                'db_table': 'wishlist',
            },
        ),
        migrations.CreateModel(
            name='ShopperReview',
            fields=[
                ('id_review_shopper', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('id_real_deal', models.ForeignKey(db_column='id_real_deal', on_delete=django.db.models.deletion.DO_NOTHING, to='member.RealDeal')),
            ],
            options={
                'db_table': 'shopper_review',
            },
        ),
        migrations.CreateModel(
            name='ShopperRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_rate', models.ForeignKey(db_column='id_rate', on_delete=django.db.models.deletion.DO_NOTHING, to='member.Rate')),
                ('id_review_shopper', models.ForeignKey(db_column='id_review_shopper', on_delete=django.db.models.deletion.DO_NOTHING, to='member.ShopperReview')),
            ],
            options={
                'db_table': 'shopper_rate',
            },
        ),
        migrations.CreateModel(
            name='SellerReview',
            fields=[
                ('id_review_seller', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('id_real_deal', models.ForeignKey(db_column='id_real_deal', on_delete=django.db.models.deletion.DO_NOTHING, to='member.RealDeal')),
            ],
            options={
                'db_table': 'seller_review',
            },
        ),
        migrations.CreateModel(
            name='SellerRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_rate', models.ForeignKey(db_column='id_rate', on_delete=django.db.models.deletion.DO_NOTHING, to='member.Rate')),
                ('id_review_seller', models.ForeignKey(db_column='id_review_seller', on_delete=django.db.models.deletion.DO_NOTHING, to='member.SellerReview')),
            ],
            options={
                'db_table': 'seller_rate',
            },
        ),
        migrations.CreateModel(
            name='MemberShopper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_member', models.ForeignKey(db_column='id_member', on_delete=django.db.models.deletion.DO_NOTHING, to='member.Member')),
                ('id_real_deal', models.ForeignKey(db_column='id_real_deal', on_delete=django.db.models.deletion.DO_NOTHING, to='member.RealDeal')),
            ],
            options={
                'db_table': 'member_shopper',
            },
        ),
        migrations.CreateModel(
            name='MemberSeller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_member', models.ForeignKey(db_column='id_member', on_delete=django.db.models.deletion.DO_NOTHING, to='member.Member')),
                ('id_real_deal', models.ForeignKey(db_column='id_real_deal', on_delete=django.db.models.deletion.DO_NOTHING, to='member.RealDeal')),
            ],
            options={
                'db_table': 'member_seller',
            },
        ),
        migrations.CreateModel(
            name='Memberaddr',
            fields=[
                ('id_member_addr', models.AutoField(primary_key=True, serialize=False)),
                ('addr', models.CharField(max_length=200)),
                ('id_member', models.ForeignKey(db_column='id_member', on_delete=django.db.models.deletion.DO_NOTHING, to='member.Member')),
            ],
            options={
                'db_table': 'memberaddr',
            },
        ),
        migrations.CreateModel(
            name='MannerReviewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_manner_log', models.ForeignKey(blank=True, db_column='id_manner_log', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='member.MannerLog')),
                ('reviewer', models.ForeignKey(db_column='reviewer', on_delete=django.db.models.deletion.DO_NOTHING, to='member.Member')),
            ],
            options={
                'db_table': 'manner_reviewer',
            },
        ),
        migrations.AddField(
            model_name='manner',
            name='id_member',
            field=models.ForeignKey(db_column='id_member', on_delete=django.db.models.deletion.DO_NOTHING, to='member.Member'),
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id_log', models.AutoField(primary_key=True, serialize=False)),
                ('search', models.CharField(max_length=60)),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('id_member', models.ForeignKey(db_column='id_member', on_delete=django.db.models.deletion.DO_NOTHING, to='member.Member')),
            ],
            options={
                'db_table': 'log',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id_company', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('addr', models.CharField(max_length=200)),
                ('tel', models.CharField(blank=True, max_length=20, null=True)),
                ('info', models.CharField(blank=True, max_length=3000, null=True)),
                ('category', models.CharField(blank=True, max_length=15, null=True)),
                ('img', models.CharField(blank=True, max_length=2000, null=True)),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id_member', models.ForeignKey(db_column='id_member', on_delete=django.db.models.deletion.DO_NOTHING, to='member.Member')),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='NearbyLocations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nearby_dong', models.CharField(max_length=20)),
                ('distance', models.IntegerField()),
                ('dong', models.ForeignKey(db_column='dong', on_delete=django.db.models.deletion.DO_NOTHING, to='member.Location', unique=True)),
            ],
            options={
                'db_table': 'nearby_locations',
                'unique_together': {('dong', 'nearby_dong', 'distance')},
            },
        ),
    ]
