# Generated by Django 3.0.3 on 2020-07-08 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NearbyLocation',
            fields=[
                ('dong', models.OneToOneField(db_column='dong', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='member.Location')),
                ('nearby_dong', models.CharField(max_length=20)),
                ('distance', models.IntegerField()),
            ],
            options={
                'db_table': 'nearby_location',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='membershopper',
            name='id_member',
        ),
        migrations.RemoveField(
            model_name='membershopper',
            name='id_real_deal',
        ),
        migrations.AlterUniqueTogether(
            name='nearbylocations',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='nearbylocations',
            name='dong',
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='log',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='manner',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='mannerlog',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='mannerreviewer',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='memberaddr',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='rate',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='realdeal',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='sellerrate',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='sellerreview',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='shopperrate',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='shopperreview',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='wishlist',
            options={'managed': False},
        ),
        migrations.DeleteModel(
            name='MemberSeller',
        ),
        migrations.DeleteModel(
            name='MemberShopper',
        ),
        migrations.DeleteModel(
            name='NearbyLocations',
        ),
    ]
