# Generated by Django 3.0.3 on 2020-05-28 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MannerReviewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'manner_reviewer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MemberSeller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'member_seller',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MemberShopper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'member_shopper',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id_rate', models.IntegerField(primary_key=True, serialize=False)),
                ('field', models.CharField(max_length=8)),
                ('detail', models.CharField(max_length=50)),
                ('score', models.IntegerField()),
            ],
            options={
                'db_table': 'rate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SellerRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'seller_rate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShopperRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'shopper_rate',
                'managed': False,
            },
        ),
    ]
