# Generated by Django 3.0.3 on 2020-06-15 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_mannerreviewer_memberseller_membershopper_rate_sellerrate_shopperrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('dong', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=0, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
            options={
                'db_table': 'location',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MannerLog',
            fields=[
                ('id_manner_log', models.IntegerField(primary_key=True, serialize=False)),
                ('score', models.FloatField()),
                ('cdate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'manner_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Memberaddr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addr', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'memberaddr',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NearbyLocations',
            fields=[
                ('dong', models.ForeignKey(db_column='dong', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='member.Location')),
                ('nearby_dong', models.CharField(max_length=20)),
                ('distance', models.IntegerField()),
            ],
            options={
                'db_table': 'nearby_locations',
                'managed': False,
            },
        ),
    ]
