# Generated by Django 3.0.3 on 2020-07-06 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfilemodel',
            name='id_product',
            field=models.ForeignKey(db_column='id_product', on_delete=django.db.models.deletion.CASCADE, to='member.Product'),
        ),
    ]
